### ISSUE TITLE
Legg til dataset-types fra publications.europa.eu

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-reference-data#141]
Skal legges til som `/eu/data-types`, kan sannsynligvis ta utgangspunkt i de andre eu-ressursene, feks data-themes

ref `http://publications.europa.eu/resource/authority/dataset-type`

-----
https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/534
https://github.com/Informasjonsforvaltning/behov/issues/759
https://github.com/Informasjonsforvaltning/behov/issues/758

**Comment by KurtStian** [comment]
@NilsOveTen Vokabularet `http://publications.europa.eu/resource/authority/dataset-type` er anbefalt å bruke, jf: https://data.norge.no/specification/dcat-ap-no#B%C3%B8r-brukes-for-type
Det betyr at ved høsting så kan datatype være skos:preflabel slik at denne informasjonen må behandles. Men det kan kun være en datasett-type, jf: https://data.norge.no/specification/dcat-ap-no#Datasett-type
