### ISSUE TITLE
Skrive om hvordan vi mapper json-filer i reference-data

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-reference-data#41]
Dette gjøres nå på en veldig komplisert måte. Kan vi refaktorere og gjøre dette enklere?
F.eks sette opp et springAPI ?

- [x]  Refaktorere deler av codes ( se Else { ) 

- [ ] vurdere om vi skal svare med RDF i tillegg?

**Comment by matsjs** [comment]
https://github.com/Informasjonsforvaltning/fdk-reference-data/pull/40

**Comment by shenluna** [comment]
Refaktorering av kode, ikke sett eller opplevd noen problemer etter merge. Lukker saken
