### ISSUE TITLE
Legg til beskrivelse av kodene til organisasjonsform, næringskode og sektorkode

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-reference-data#45]
> Approver. Har to spørsmål (som ikkje er showstoppers):
> 
> * Meiner å hugse at den gamle implementasjonen hadde noko spes rundt transportportal. Vi må passe på at transportportal også er støtta i ny versjon.
> * Ser at vi stadig må til data.brreg.no for eit par ting. Hadde det vore ein idé å utvide organization-catalogue med disse properties?

De andre verdiene vi bruker er beskrivelse av kodene til organisasjonsform, næringskode og sektorkode, hadde vært mer for å ta det inn i reference-data.

_Originally posted by @NilsOveTen in https://github.com/Informasjonsforvaltning/fdk-organization-bff/pull/56#issuecomment-817558267_

**Comment by KjerstiSteien** [comment]
@NilsOveTen fortsatt relevant?

**Comment by NilsOveTen** [comment]
> @NilsOveTen fortsatt relevant?

Ja, men dette er en kopi av #140, kan fint lukke denne.
