### ISSUE TITLE
Unable to harvest eurovoc

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-reference-data#73]
> jsonPayload: {
> logger_name: "no.fdk.referencedata.eu.eurovoc.EuroVocService"
> message: "Unable to harvest eurovoc"
> stack_hash: "a87ab6d0"
> stack_trace: "j.l.NumberFormatException: multiple points
> 	at j.i.m.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
> 	at j.i.m.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> 	at java.lang.Double.parseDouble(Double.java:549)
> 	at n.f.r.e.e.EuroVocService.harvestAndSave(EuroVocService.java:38)
> 	at n.f.r.Scheduler.updateEuroVoc(Scheduler.java:93)
> 	at j.i.r.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
> 	at j.i.r.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
> 	at j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at j.l.reflect.Method.invoke(Method.java:564)
> 	at o.s.s.s.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
> 	at o.s.s.s.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
> 	at o.s.s.c.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
> 	at j.u.c.Executors$RunnableAdapter.call(Executors.java:515)
> 	at j.u.c.FutureTask.run(FutureTask.java:264)
> 	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
> 	at j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 	at j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 	at java.lang.Thread.run(Thread.java:832)
> "
> timestamp: "2021-12-21T03:30:00.390+01:00"
> }

**Comment by valosnah** [comment]
For ordens skyld, dette gjelder new-reference-data

**Comment by jeffreiffers** [comment]
Har laget en fix på dette. Men ser at også distribusjonsfila ikke finnes lenger. Og lasted ned Eurovoc som rdf går ikke siden den er for stor.
